### ISSUE TITLE
stalled in RUNNING INFERENCE stage

### ISSUE THREAD

**Issue by lbal-biomat** [kishwarshafin/pepper#29] opened 2021-01-05 19:29 UTC
Hi, 

I installed pepper v 0.1.5 with pip and tried to run `pepper polish` (cpu) but it's stalled on the RUNNING INFERENCE stage, here is the log:
```
[01-05-2021 14:35:34] INFO: FINISHED IMAGE GENERATION
[01-05-2021 14:35:34] INFO: ELAPSED TIME: 11 Min 52 Sec
[01-05-2021 14:35:34] STEP 2: RUNNING INFERENCE
[01-05-2021 14:35:34] INFO: PREDICTION OUTPUT: pepper/predictions_01052021_142341/
[01-05-2021 14:35:34] INFO: DISTRIBUTED CPU SETUP
[01-05-2021 14:35:34] INFO: SETUP: 
[01-05-2021 14:35:34] INFO: TOTAL CALLERS: 28
[01-05-2021 14:35:34] INFO: THREADS PER CALLER: 1
[01-05-2021 14:35:34] INFO: DATA-LOADER PER CALLER: 4
[01-05-2021 14:35:34] INFO: MODEL LOADING TO ONNX
[01-05-2021 14:35:34] INFO: SAVING MODEL TO ONNX
```
And it's stalled there. It doesn't raise any error, but it's not running either. 
The file `R10.3_models_PEPPER_polish_R10.3.pkl.onnx` is created in the same directory provided for the model. 
After I terminate the process I get this traceback:
```
Traceback (most recent call last):
  File "/home/lucia/.local/lib/python3.8/site-packages/pepper/modules/python/models/predict_distributed_cpu.py", line 154, in predict_cpu
    for fut in concurrent.futures.as_completed(futures):
  File "/media3/lucia/env/lib/python3.8/concurrent/futures/_base.py", line 244, in as_completed
    waiter.event.wait(wait_timeout)
  File "/media3/lucia/env/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/media3/lucia/env/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
```
Here is the line I used to call pepper:
```
 pepper polish -b map.bam -f assembly-raw.fasta -m /path/to/R10.3_models_PEPPER_polish_R10.3.pkl -t 28 -o pepper
```
Any sugestions?

Thanks,

L.

**Comment by kishwarshafin** [comment] 2021-01-05 22:28
@lbal-biomat , can you please run the pipeline again and look at CPU utilization during inference to know for sure that the process is stuck and not that it's not printing things so it feels stuck?

**Comment by lbal-biomat** [comment] 2021-01-06 00:39
Hi, thanks for your quick answer.

I don't think it's running at all, I let it stew for a while. This is the `htop` view after it stops printing:
![Selección_005](https://user-images.githubusercontent.com/76665262/103714305-196d8600-4f9d-11eb-970f-f3bda169e2b3.png)

Another quite weird thing is that I can still see the pepper processes after I stop the program, and even after I logout and login again:
![Selección_004](https://user-images.githubusercontent.com/76665262/103714481-8254fe00-4f9d-11eb-8ef5-e66ed9de9cdb.png)

Thanks

**Comment by kishwarshafin** [comment] 2021-01-06 06:02
@lbal-biomat ,

Thank you for the details. I am trying to reproduce this issue locally but can't so far. In the meantime, while I debug, would it be possible for you to run `pepper` via docker and see if it's still the same?

```bash
docker run --ipc=host \
-v /data:/data \
kishwars/pepper:0.1.5 \
pepper --version
```
Please let me know if you need help with running docker, I can walk you through the process.

**Comment by lbal-biomat** [comment] 2021-01-06 11:32
@kishwarshafin,

Thanks for looking into it. I will definitely try running `pepper` via docker. I'm trying out different polishing pipelines and so far marginPolish+HELEN gives the best results by far, so I'm excited to check what `pepper` can do.
I'll let you know if I need help, thanks so much for your time.

**Comment by kishwarshafin** [comment] 2021-01-06 23:10
@lbal-biomat , 

Thanks for trying out our pipelines! Can you please let me know if the docker version worked for you? I'm having trouble regenerating your issue locally. I possibly will have to postpone this for a while and take a closer look later if this doesn't need immediate attention.

**Comment by lbal-biomat** [comment] 2021-01-07 22:11
Hi,
I'm running it right now and is run without any problem.
Thanks for your help, I appreciate it. And thanks for this great pipelines!

**Comment by kishwarshafin** [comment] 2021-02-24 16:40
@lbal-biomat , 

We were able to re-generate this issue internally. It happens because of ONNX version mismatch. This issue will be resolved in the next version of PEPPER. I'm closing this for now.

**Closed as completed by kishwarshafin** 2021-02-24 16:41 UTC
