### ISSUE TITLE
ERROR: basic_string::substr

### ISSUE THREAD

**Issue by chilampoon** [kishwarshafin/pepper#168] opened 2022-09-24 21:51 UTC
Hi Kishwar,

I got these errors when I ran singularity pepper on a mouse dataset (output bam file from Sockeye):

```
[09-24-2022 17:30:09] INFO: ONT VARIANT CALLING MODE SELECTED.
[09-24-2022 17:30:09] INFO: MODE: PEPPER
[09-24-2022 17:30:09] INFO: THRESHOLDS ARE SET TO: 
[09-24-2022 17:30:09] INFO: MIN MAPQ:				5
[09-24-2022 17:30:09] INFO: MIN SNP BASEQ:			1
[09-24-2022 17:30:09] INFO: MIN INDEL BASEQ:			1
[09-24-2022 17:30:09] INFO: MIN SNP FREQUENCY:			0.1
[09-24-2022 17:30:09] INFO: MIN INSERT FREQUENCY:		0.15
[09-24-2022 17:30:09] INFO: MIN DELETE FREQUENCY:		0.15
[09-24-2022 17:30:09] INFO: MIN COVERAGE THRESHOLD:		3
[09-24-2022 17:30:09] INFO: MIN CANDIDATE SUPPORT:		2
[09-24-2022 17:30:09] INFO: MIN SNP CANDIDATE FREQUENCY:	0.1
[09-24-2022 17:30:09] INFO: MIN INDEL CANDIDATE FREQUENCY:	0.1
[09-24-2022 17:30:09] INFO: SKIP INDEL CANDIDATES:		False
[09-24-2022 17:30:09] INFO: MAX ALLOWED CANDIDATE IN ONE SITE:	4
[09-24-2022 17:30:09] INFO: MIN SNP PREDICTIVE VALUE:		0.1
[09-24-2022 17:30:09] INFO: MIN INSERT PREDICTIVE VALUE:	0.1
[09-24-2022 17:30:09] INFO: MIN DELETE PREDICTIVE VALUE:	0.1
[09-24-2022 17:30:09] INFO: SNP QV CUTOFF FOR RE-GENOTYPING:	20
[09-24-2022 17:30:09] INFO: INDEL QV CUTOFF FOR RE-GENOTYPING:	15
[09-24-2022 17:30:09] INFO: REPORT ALL SNPs ABOVE THRESHOLD:	0
[09-24-2022 17:30:09] INFO: REPORT ALL INDELs ABOVE THRESHOLD:	0
[09-24-2022 17:30:09] INFO: LOW COMPLEXITY REGION SETUP:
[09-24-2022 17:30:09] INFO: MIN SNP PREDICTIVE VALUE:		0.1
[09-24-2022 17:30:09] INFO: MIN INSERT PREDICTIVE VALUE:	0.15
[09-24-2022 17:30:09] INFO: MIN DELETE PREDICTIVE VALUE:	0.1
[09-24-2022 17:30:09] INFO: SNP QV CUTOFF FOR RE-GENOTYPING:	20
[09-24-2022 17:30:09] INFO: INDEL QV CUTOFF FOR RE-GENOTYPING:	10
[09-24-2022 17:30:09] INFO: CALL VARIANT MODULE SELECTED
[09-24-2022 17:30:09] INFO: RUN-ID: 09242022_173009
[09-24-2022 17:30:09] INFO: IMAGE OUTPUT: /gpfs/commons/home/cpoon/deepvariant_try/output/pepper/images_09242022_173009/
[09-24-2022 17:30:09] INFO: STEP 1/3 GENERATING IMAGES:
[09-24-2022 17:30:09] INFO: COMMON CONTIGS FOUND: ['GL456210.1', 'GL456211.1', 'GL456212.1', 'GL456213.1', 'GL456216.1', 'GL456219.1', 'GL456221.1', 'GL456233.1', 'GL456239.1', 'GL456350.1', 'GL456354.1', 'GL456359.1', 'GL456360.1', 'GL456366.1', 'GL456367.1', 'GL456368.1', 'GL456370.1', 'GL456372.1', 'GL456378.1', 'GL456379.1', 'GL456381.1', 'GL456382.1', 'GL456383.1', 'GL456385.1', 'GL456387.1', 'GL456389.1', 'GL456390.1', 'GL456392.1', 'GL456393.1', 'GL456394.1', 'GL456396.1', 'JH584292.1', 'JH584293.1', 'JH584294.1', 'JH584295.1', 'JH584296.1', 'JH584297.1', 'JH584298.1', 'JH584299.1', 'JH584300.1', 'JH584301.1', 'JH584302.1', 'JH584303.1', 'JH584304.1', 'chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chrM', 'chrX', 'chrY']
[09-24-2022 17:30:09] INFO: TOTAL CONTIGS: 66 TOTAL INTERVALS: 27348 TOTAL BASES: 2730871708
[09-24-2022 17:30:09] INFO: STARTING PROCESS: 0 FOR 4558 INTERVALS
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ERROR: basic_string::substr: __pos (which is 1084) > this->size() (which is 714)
ERROR: basic_string::substr: __pos (which is 8884) > this->size() (which is 1003)
ERROR: basic_string::substr: __pos (which is 1361) > this->size() (which is 578)
ERROR: basic_string::substr: __pos (which is 1356) > this->size() (which is 644)
ERROR: basic_string::substr: __pos (which is 2712) > this->size() (which is 1818)
ERROR: basic_string::substr: __pos (which is 22132) > this->size() (which is 1294)
[09-24-2022 17:30:09] INFO: FINISHED IMAGE GENERATION
[09-24-2022 17:30:09] INFO: TOTAL ELAPSED TIME FOR GENERATING IMAGES: 0 Min 0 Sec
[09-24-2022 17:30:09] INFO: STEP 2/3 RUNNING INFERENCE
```
How do I resolve this issue? Thank you very much.

**Comment by kishwarshafin** [comment] 2022-09-24 22:06
@chilampoon ,

Is it possible to check if you are using the right reference against the bam file? Much easier if you can give me a small bam and fasta to see if I can reproduce this locally.

**Comment by chilampoon** [comment] 2022-09-25 18:02
@kishwarshafin sure -
* a small subset of my bam: https://drive.google.com/file/d/1UbeoCf4iZHyWDeQPDpxJcaz4i2OBOZg-/view?usp=sharing
* reference fasta `mm10_2020_A.fa.gz`: https://drive.google.com/file/d/1M6_MOUgRlnzhh6rFcmTuzjXvLas10kb4/view?usp=sharing

**Comment by kishwarshafin** [comment] 2022-09-26 19:19
@chilampoon ,

Thank you, I'll make some time to look at this by the end of this week but please expect a bit of a delay because of a tight schedule. Thank you very much for sharing the data!

**Comment by kishwarshafin** [comment] 2023-03-18 18:01
Hi @chilampoon , 

I was unable to resolve this issue, I am marking this as won't fix.

**Closed as not planned by kishwarshafin** 2023-03-18 18:01 UTC
