### ISSUE TITLE
No luck compiling pepper v0.1 under Anaconda3/2020.07 

### ISSUE THREAD

**Issue by ponomarevsy** [kishwarshafin/pepper#31] opened 2021-01-12 16:05 UTC
Installation of Pepper via conda ("python3 -m pip install pepper-polish") or directly from the repo ("pip install -e .") under Anaconda3/2020.07 environment (Python 3.8.6) fails with:

```
  Building wheel for pepper-polish (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /path/Anaconda3/2020.07/envs/pepper-0.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vsj21207/pepper-polish_31202eea9eea4b528636689f478df8d8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vsj21207/pepper-polish_31202eea9eea4b528636689f478df8d8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l5wltpwe
       cwd: /tmp/pip-install-vsj21207/pepper-polish_31202eea9eea4b528636689f478df8d8/
```

and

```
  [ 21%] No update step for 'htslib'
  [ 28%] No patch step for 'htslib'
  [ 35%] Performing configure step for 'htslib'
  Can't load '/path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so' for module Fcntl: /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so: undefined symbol: Perl_xs_boot_epilog at /path/Anaconda3/2020.07/lib/5.26.2/XSLoader.pm line 96.
   at /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/Fcntl.pm line 66.
  Compilation failed in require at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
  BEGIN failed--compilation aborted at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
  Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
  BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
  Compilation failed in require at /usr/bin/autom4te line 40.
  BEGIN failed--compilation aborted at /usr/bin/autom4te line 40.
  gmake[2]: *** [htslib/src/htslib-stamp/htslib-configure] Error 2
  gmake[1]: *** [CMakeFiles/htslib.dir/all] Error 2
  gmake: *** [all] Error 2
...
  ----------------------------------------
  ERROR: Failed building wheel for pepper-polish
```
Please let me know if you have any ideas on how to resolve this issue. The following libraries were installed (but did not help much):

```
conda install -c anaconda protobuf
conda install pybind11 -c conda-forge
conda install -c bioconda htslib 
```

**Comment by kishwarshafin** [comment] 2021-01-12 16:07
@ponomarevsy , can you please try PEPPER via docker and see if it works?

```bash
docker run --ipc=host \
-v /data:/data \
kishwars/pepper:0.1.5 \
pepper --version
```

**Comment by ponomarevsy** [comment] 2021-01-12 16:13
Thanks, @kishwarshafin! We don't use docker in our HPC environment... I could try converting a Docker image to Singularity but this will take some time. Anything else we could do? Please let me know.

**Comment by kishwarshafin** [comment] 2021-01-12 17:19
@ponomarevsy ,

Can you please try running the docker like this:
```bash
singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper:0.1.5 pepper --version 
```

**Comment by ponomarevsy** [comment] 2021-01-12 17:46
Thank you, @kishwarshafin. This looks better but fails the final step: 

```
» singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://kishwars/pepper:0.1.5 pepper --version ~/eb_files/Pepper
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:54ee1f796a1e650627269605cb8e6a596b77b324e6f0a1e4443dc41def0e58a6
 27.24 MiB / 27.24 MiB [====================================================] 0s
Copying blob sha256:f7bfea53ad120b47cea5488f0b8331e737a97b33003517b0bd05e83925b578f0
 31.58 KiB / 31.58 KiB [====================================================] 0s
Copying blob sha256:46d371e02073acecf750a166495a63358517af793de739a51b680c973fae8fb9
 848 B / 848 B [============================================================] 0s
Copying blob sha256:b66c17bbf772fa072c280b10fe87bc999420042b5fce5b111db38b4fe7c40b49
 162 B / 162 B [============================================================] 0s
Copying blob sha256:3642f1a6dfb3bdd5ba6a8173363fe58bf4d46a01fa3f4b3907a1e60b803527bf
 7.56 MiB / 7.56 MiB [======================================================] 0s
Copying blob sha256:e5ce55b8b4b9ff443d9de73e100d843d57d8708ebaef7bbc33c0c0544c14d1b1
 9.78 MiB / 9.78 MiB [======================================================] 0s
Copying blob sha256:155bc0332b0a8aee5dad9ff6e67299b34ed4cd81d5a6a0a75418b7f48f378998
 1.01 KiB / 1.01 KiB [======================================================] 0s
Copying blob sha256:95314a8d8730ebe9ef49d9b7fa2a3572e5c58a27ad2400ff3107f8fed75d7d43
 151.78 MiB / 151.78 MiB [==================================================] 7s
Copying blob sha256:5ef9f705059e70c6208d79bc7bc3c17ef96ad057422bc7a6b1d7e70097cbd8e6
 184 B / 184 B [============================================================] 0s
Copying blob sha256:fa3c553519d0a6e2c12f19b20322f0fbfe616369adf6d55a0b9f157b2664ee63
 257 B / 257 B [============================================================] 0s
Copying blob sha256:75829162197855eac2848608d88b11bb4df807c5532902c12c95577624812bd2
 1.99 GiB / 1.99 GiB [===================================================] 5m44s
Copying config sha256:1493a50e385ef613a4e37ba0e1981c73001bdb3fefabecc467f7eb39c66a0b60
 7.93 KiB / 7.93 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /nethome/appbuild/.singularity/cache/oci-tmp/3a05109b36b6cfed9f041bf2701354c62f1975e020b4587f578a30db1fd5057a/pepper_0.1.5.sif
FATAL:   container creation failed: mount /proc/self/fd/6->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/6: failed to mount squashfs filesystem: no such device
```

**Comment by ponomarevsy** [comment] 2021-01-15 15:48
Just wondering if you have any other ideas on how to make pepper work... I could try a different Anaconda and a different Python version. Any insight on why Singularity container building fails, @kishwarshafin?

**Comment by kishwarshafin** [comment] 2021-01-15 21:28
@ponomarevsy , 

Sorry for the late reply. Would it be possible to manually create a virtual environment from your native python (not conda) and try to install PEPPER? So the process would look like this:
```bash
git clone https://github.com/kishwarshafin/pepper.git
cd pepper
virtualenv venv --python=/path/to/native/python3 --prompt "(pepper) "
source ./venv/bin/activate
python3 setup.py install
```

**Comment by ponomarevsy** [comment] 2021-01-15 22:21
We don't have virtualenv defined in RHEL 7, so, it doesn't go beyond "zsh: command not found: virtualenv"

Is it Perl or htslib that fails (please see below)? Can the 'htslib' package be skipped during the installation process? 
```
» python3 setup.py install
...
-- Downloading... done
-- extracting...
     src='/path/Pepper/pepper/build/temp.linux-x86_64-3.8/htslib/src/htslib-1.9.tar.bz2'
     dst='/path/Pepper/pepper/build/temp.linux-x86_64-3.8/htslib/src/htslib'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 21%] No update step for 'htslib'
[ 28%] No patch step for 'htslib'
[ 35%] Performing configure step for 'htslib'
Can't load '/path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so' for module Fcntl: /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so: undefined symbol: Perl_xs_boot_epilog at /path/Anaconda3/2020.07/lib/5.26.2/XSLoader.pm line 96.
 at /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/Fcntl.pm line 66.
Compilation failed in require at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
BEGIN failed--compilation aborted at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
Compilation failed in require at /usr/bin/autom4te line 40.
BEGIN failed--compilation aborted at /usr/bin/autom4te line 40.
gmake[2]: *** [htslib/src/htslib-stamp/htslib-configure] Error 2
gmake[1]: *** [CMakeFiles/htslib.dir/all] Error 2
gmake: *** [all] Error 2
...
```

Besides, it is already installed in conda:

```
» conda list htslib                                                                     
# packages in environment at /path/Anaconda3/2020.07/envs/pepper-0.1:
#
# Name                    Version                   Build  Channel
htslib                    1.9                  ha228f0b_7    bioconda
```

**Comment by kishwarshafin** [comment] 2021-01-16 05:33
@ponomarevsy ,

`htslib` is essential for `PEPPER`. Also, `can't mount image /proc/self/fd/6: failed to mount squashfs filesystem: no such device` is a system-specific error. I'm not exactly sure how to go from here. I will try to build a clean singularity executable for the next release which will hopefully solve this issue. But, I don't have any immediate solution for you.

**Comment by kishwarshafin** [comment] 2021-03-05 01:55
@ponomarevsy , 

We just released a new version with full singularity support. Can you please try this version and let me know if it works? Closing this for now.

**Comment by ponomarevsy** [comment] 2021-03-05 20:40
Unfortunately, I am getting the same errors as above for v0.4, i.e.:
```
 [ 21%] No update step for 'htslib'
  [ 28%] No patch step for 'htslib'
  [ 35%] Performing configure step for 'htslib'
  Can't load '/path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so' for module Fcntl: /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so: undefined symbol: Perl_xs_boot_epilog at /path/Anaconda3/2020.07/lib/5.26.2/XSLoader.pm line 96.
   at /path/Anaconda3/2020.07/lib/5.26.2/x86_64-linux-thread-multi/Fcntl.pm line 66.
  Compilation failed in require at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
  BEGIN failed--compilation aborted at /path/Anaconda3/2020.07/lib/5.26.2/File/stat.pm line 30.
  Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
  BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 40.
  Compilation failed in require at /usr/bin/autom4te line 40.
  BEGIN failed--compilation aborted at /usr/bin/autom4te line 40.
  gmake[2]: *** [htslib/src/htslib-stamp/htslib-configure] Error 2
  gmake[1]: *** [CMakeFiles/htslib.dir/all] Error 2
  gmake: *** [all] Error 2
...
  ----------------------------------------
  ERROR: Failed building wheel for pepper-polish
```
when running:
```
python3 setup.py install
```
What would the Singularity command be for the new release? Thank you!

**Comment by kishwarshafin** [comment] 2021-03-08 04:26
@ponomarevsy , 

Can you please try this:
```bash
# This is a 6.6GB download
singularity pull docker://kishwars/pepper_deepvariant:r0.4
# This will download pepper_deepvariant_r0.4.sif

# PEPPER SNP
singularity exec --bind /usr/lib/locale/ \
pepper_deepvariant_r0.4.sif \
pepper_snp --help
```

Also, there are several documentations available that you can follow: https://github.com/kishwarshafin/pepper

**Comment by ponomarevsy** [comment] 2021-03-09 23:05
Okey, thank you. Here is what I have:
```
» singularity pull docker://kishwars/pepper_deepvariant:r0.4
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:f22ccc0b8772d8e1bcb40f137b373686bc27427a70c0e41dd22b38016e09e7e0
 25.47 MiB / 25.47 MiB [====================================================] 0s
Copying blob sha256:3cf8fb62ba5ffb221a2edb2208741346eb4d2d99a174138e4afbb69ce1fd9966
 850 B / 850 B [============================================================] 0s
Copying blob sha256:e80c964ece6a3edf0db1cfc72ae0e6f0699fb776bbfcc92b708fbb945b0b9547
 162 B / 162 B [============================================================] 0s
Copying blob sha256:a0afc6a191249d59588fdb8c17d1f6b3c2700c03cc5bd338144b860963507a51
 6.90 MiB / 6.90 MiB [======================================================] 0s
Copying blob sha256:18287e0c259e858d7a07ff130a7c990f860be7137ef1bacd13ee3a337a4aafba
 8.08 MiB / 8.08 MiB [======================================================] 0s
Copying blob sha256:88c0e0db918c9519d7e6d22439e2fc61b18836b6291e777121010d6baef58acc
 187 B / 187 B [============================================================] 0s
Copying blob sha256:c2899c05e34e0eb086fe2f56b93dad27660c62f916557e59656365559dc2e7cc
 633.77 MiB / 633.77 MiB [=================================================] 12s
Copying blob sha256:d94f5100467de1f18131ae3b55817938fd48ecf9409360974a21ea66d29278cb
 61.31 KiB / 61.31 KiB [====================================================] 0s
Copying blob sha256:8064d28d9c5771b883e0a7570c8d82e536e165dae5ff70f5529fd40df20b753d
 772.96 MiB / 772.96 MiB [=================================================] 14s
Copying blob sha256:60cfda626d91aa8da62114679d1031bd0fb8aa1782a3b44afe60e004b6c2381a
 85.64 KiB / 85.64 KiB [====================================================] 0s
Copying blob sha256:45e3705616204046ce2245b8b1ecd9b9d011a541a63af5d593a49b27615028b6
 507.75 MiB / 507.75 MiB [=================================================] 10s
Copying blob sha256:b0f82aee995da28a7337c9d05513aef5b248581a72dfc65594f47cda9f64e9c6
 186 B / 186 B [============================================================] 0s
Copying blob sha256:455597744e09a14a8dc2bbbdeb78ee734f03cb7f831be381d5fb653af30beee5
 18.41 KiB / 18.41 KiB [====================================================] 0s
Copying blob sha256:89622913842a9bc40968352ef027f63b9a45ba6118208211d268463e4cf54f84
 170 B / 170 B [============================================================] 0s
Copying blob sha256:699ac15b34664a3f48637627d95e930ce25896dd902a250a860a637fd03fac10
 3.85 KiB / 3.85 KiB [======================================================] 0s
Copying blob sha256:85879ea11c3add2c5942a20c10ec00e1624c6f35763cd29d7adc757f9b89d468
 2.87 KiB / 2.87 KiB [======================================================] 0s
Copying blob sha256:8d57905336ae4f8946a9810990f95b230bccc9d020129ba6b3103bf96a7de4e2
 6.77 MiB / 6.77 MiB [======================================================] 0s
Copying blob sha256:23389d7c8ce076f36840d5e4345f20ab48532f1ed0e7ca3b697439601740012b
 6.70 MiB / 6.70 MiB [======================================================] 0s
Copying blob sha256:883080ce322a6f31b7d194df08871e680831e1b221116e857acfd6c60d6b524f
 6.73 MiB / 6.73 MiB [======================================================] 0s
Copying blob sha256:9e12c5410db4b069c1fc16522d89d22644058630428795b971738f3f3f6dbdf1
 6.65 MiB / 6.65 MiB [======================================================] 0s
Copying blob sha256:1f2efffcd73248646c21f52f42019f30da52e7d7b90ba20c86bda1fa5e561776
 6.64 MiB / 6.64 MiB [======================================================] 0s
Copying blob sha256:3aeeda43f61f7f45d0a76b2668ce8844a0af5cf520ed17072f770757891f1484
 125.79 KiB / 125.79 KiB [==================================================] 0s
Copying blob sha256:34cbac2f3b5dba15a7b22d0a7fd449396391e0eab726bd25320d1c3b99cf7c8f
 6.69 MiB / 6.69 MiB [======================================================] 0s
Copying blob sha256:ef872858fa248de14721f976486849f13147dcd5f3525a1ce82f41a98af63b11
 6.69 MiB / 6.69 MiB [======================================================] 0s
Copying blob sha256:284e0dbd098bb0b907ba6bfba0bf534a6cf1749d6e5eee2cd48a79fe4653fc4c
 5.06 KiB / 5.06 KiB [======================================================] 0s
Copying blob sha256:a1ae0bf1ce47f25c5e44f57d1db96d93e2a28cfa6e622752a493f97b7471e0ee
 939.53 MiB / 939.53 MiB [=================================================] 19s
Copying blob sha256:ba17b68c43b898bdfcae0b799066b9a5fdd3a6ca4b2ca27212cfddc13a1205cd
 471 B / 471 B [============================================================] 0s
Copying blob sha256:0c11bddf421441e2a93f4043a5533794d67a5d014950bea1d3eaaf4945710f90
 167 B / 167 B [============================================================] 0s
Copying blob sha256:1613885b72bbc0c0983bc0f7c7913df6299316be53e7141381377c4c9d8815f2
 282.59 MiB / 282.59 MiB [=================================================] 27s
Copying blob sha256:0cd169bb94ab62cda9f122ca212af8ac9a2c3d284433f71499efa1509aa56cb5
 15.37 KiB / 15.37 KiB [====================================================] 0s
Copying blob sha256:2f4aae9f3f7805ad0e01899e13ba04aa8b6613b91628c35487e183ab9f9aa5b3
 905.42 KiB / 905.42 KiB [==================================================] 0s
Copying blob sha256:6d5cd5440e79345f411728ff7e3a8df170bb11ca7f4c2606cc2f2d7c2961b95a
 283.49 MiB / 283.49 MiB [==================================================] 5s
Copying blob sha256:5deb2e15a705f0ee337c0ae63346b6f2974cf314cc27d4614ce1a003df8281fb
 171 B / 171 B [============================================================] 0s
Copying blob sha256:f6d7beb49537bc45ec052cc16a821228d0cae8275bfb4af9542520bb3e58d222
 282.47 MiB / 282.47 MiB [==================================================] 5s
Copying blob sha256:3df7f37d8386ee0efb7b99022ee881ed883bf4a7e68e65821431fe46c52a68f6
 15.28 KiB / 15.28 KiB [====================================================] 0s
Copying blob sha256:83d9ab410ece4939245dddf3e8160fc6ef8872ff5ee937d8e9696f882924e506
 914.83 KiB / 914.83 KiB [==================================================] 0s
Copying blob sha256:05cb5ceb1cc5f4bbeb11810d23824f2e78ea5205b4de438484ea6f3faba45b0c
 283.37 MiB / 283.37 MiB [==================================================] 6s
Copying blob sha256:ab29c6553c13774f277182154e5415497c41ba05203f818b40556fa543d6177a
 174 B / 174 B [============================================================] 0s
Copying blob sha256:b18d8c27ae91777c87fbb71d047047c114c879b6a1b5e1615e25d0bec0da0b36
 311.98 MiB / 311.98 MiB [==================================================] 6s
Copying blob sha256:e7bfba905c4ed7b5f3358e7ab4d6fd622fddd351410dc9d76e7dac36aef28401
 15.35 KiB / 15.35 KiB [====================================================] 0s
Copying blob sha256:fa6026ee33356646d392cf5951b0ca788bb56cfb8dd6ce36e8ff24ef1d2b2b50
 905.63 KiB / 905.63 KiB [==================================================] 0s
Copying blob sha256:991cc5bad4c0b50f61b13c83c9a2e1338512f5fe4086759bcec0b9ae29880a37
 312.88 MiB / 312.88 MiB [==================================================] 6s
Copying blob sha256:3cd590f689bf346bb232898126c3cee5803f31849531c1a31c7b4d2ecfaf9be0
 190 B / 190 B [============================================================] 0s
Copying blob sha256:cae7cc73b566242159f2dfbe089d6cef20fb01b2cdb9b1f5c160b9ade169d4c4
 311.53 MiB / 311.53 MiB [==================================================] 6s
Copying blob sha256:230d955df84da3e492049c0f80eaf57af8531b97abccfb7fb1880579e3eb7c03
 15.39 KiB / 15.39 KiB [====================================================] 0s
Copying blob sha256:0ab21184420af4a6bfdc52b411fae7376aa18fe5185342db8d1f18ca0d078537
 914.80 KiB / 914.80 KiB [==================================================] 0s
Copying blob sha256:01fcb9328ca60805746ca1961cbfb06ef41d5f9ea62175174f01d1b1b7c50636
 312.44 MiB / 312.44 MiB [=================================================] 29s
Copying blob sha256:2993d1b0f8d333d9edc3974f257b9e5c4a97b25b9c515b1a0feea5b4ddea1b59
 7.28 MiB / 7.28 MiB [======================================================] 0s
Copying blob sha256:0e3798a89f83448cb9512c4e7730bd0c8008555ab8d36091c51336447f37dab0
 17.30 MiB / 17.30 MiB [====================================================] 0s
Copying blob sha256:a4ff88c5229ed71e869bec95bddbec2bd3a419308062e7a188e63b089409af03
 1001.97 KiB / 1001.97 KiB [================================================] 0s
Copying blob sha256:321da7f21ae2317ea67bec5aeb08365e7f853295e989965871b4508f48fe53c3
 16.19 KiB / 16.19 KiB [====================================================] 0s
Copying blob sha256:05c9d8742f6765f329becde9fcf6683c9281a65a1bd69e0aad0dfb5a2627a716
 4.63 MiB / 4.63 MiB [======================================================] 0s
Copying blob sha256:f5cf314d3aad54cfc26ef1d99a1c1fe1e33cdd4826568025af9c33f180be05a4
 92 B / 92 B [==============================================================] 0s
Copying blob sha256:e5db3c3fe85e8222de7b7d1ae45f3eb56427e5584aa7e58d174decdcf72c6f1b
 257 B / 257 B [============================================================] 0s
Copying blob sha256:f6a0c452199e1fb5d2e86efa3e3430911681842c345849faeb32a16b2c5d0aea
 30.12 MiB / 30.12 MiB [====================================================] 2s
Copying blob sha256:4020bd700c0a087b447088a254464a140e1ca01aa37e072571755f9a4da8ba2f
 28.69 MiB / 28.69 MiB [====================================================] 0s
Copying blob sha256:15c8faaf1c476a6dff75ce374964c6eeb3f77b4fb73d95770ec87d3a91506339
 21.88 MiB / 21.88 MiB [====================================================] 2s
Copying blob sha256:465b9858c4891a521bdaaae923c70ef7176838e1e2ed1f95f1f422d3d066ec20
 46.41 MiB / 46.41 MiB [====================================================] 0s
Copying blob sha256:c14e403d8ef22ab11634ab5337d7066604af52da7f5d8cd8b39fdbd0f2820671
 1.49 GiB / 1.49 GiB [=====================================================] 31s
Copying blob sha256:e7180fe9da32b97c0cea0b2ace5e318ad986396ed66ff4d6c3035c16ec16515e
 4.02 MiB / 4.02 MiB [======================================================] 0s
Copying blob sha256:2ed0ecfb28a1d521276f4ce2b677e45caf477dd54ad857128dfac5a553541572
 128 B / 128 B [============================================================] 0s
Copying blob sha256:63d0c5f4848b2890ce60b112089ed70ceaf0de9abfeb670077bb7ed6f66370fd
 66.28 MiB / 66.28 MiB [====================================================] 1s
Copying blob sha256:5843a826decd0070ee8c0aac956e20a215996444a22ebd143f5c64594489eae3
 35.62 MiB / 35.62 MiB [====================================================] 3s
Copying blob sha256:05bede473851e168733675a5aa4fe68ccae6c359d22f9212f50186dde11b1f37
 23.46 MiB / 23.46 MiB [====================================================] 2s
Copying blob sha256:8c9ef7c3c9875f1bfbd6ba4a0a485e91322f060cf8c5b8d234ceeb58e4f19fbb
 17.19 MiB / 17.19 MiB [====================================================] 0s
Copying blob sha256:dff5287c0a536f228d0cfd0574815b99e29c51cd6490dae449d88b8cadfcbc4a
 900.18 MiB / 900.18 MiB [===============================================] 1m23s
Copying blob sha256:72d458609d85d56f7c891455eb4a8df3f43732b04d3f381091e280b6dd3ee6f4
 6.19 KiB / 6.19 KiB [======================================================] 0s
Copying blob sha256:f0a73f23d9a1d38f87b3dd05e86e3e297f03ab748a6065266f7931e628f98d04
 12.89 KiB / 12.89 KiB [====================================================] 0s
Copying blob sha256:2b0997557d260cbe553f0ce21a4f7a3d48dd071e0fc17c7b3c3ce161481538c5
 148 B / 148 B [============================================================] 0s
Copying config sha256:ab8493e8fd0cee6525c185f68251b6515411c9678a5ff00b10021a5fd5c6c282
 30.35 KiB / 30.35 KiB [====================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: pepper_deepvariant_r0.4.sif
```
and
```
» singularity exec --bind /usr/lib/locale/ \
> pepper_deepvariant_r0.4.sif \
> pepper_snp --help
FATAL:   container creation failed: mount /proc/self/fd/6->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/6: failed to mount squashfs filesystem: no such device
```

**Comment by kishwarshafin** [comment] 2021-03-10 01:11
@ponomarevsy ,

This is a system issue: https://github.com/hpcng/singularity/issues/3465

Can you please ask your admin to do this:
```bash
modprobe squashfs
```
and then try running this pipeline?

**Comment by kishwarshafin** [comment] 2021-03-11 16:51
@ponomarevsy please re-open this issue if you are still facing the error after squashfs fix.

**Closed as completed by kishwarshafin** 2021-03-11 16:51 UTC

**Comment by ponomarevsy** [comment] 2021-03-15 20:45
Thank you, @kishwarshafin! I am getting a different error now:
```
» singularity exec --bind /usr/lib/locale/ \                                                                 
> pepper_deepvariant_r0.4.sif \
> pepper_snp --help
Traceback (most recent call last):
  File "/usr/local/bin/pepper_snp", line 5, in <module>
    from pepper_snp.pepper_snp import main
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/pepper_snp.py", line 8, in <module>
    from pepper_snp.modules.python.RunInference import run_inference
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/RunInference.py", line 6, in <module>
    from pepper_snp.modules.python.models.predict import predict
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/predict.py", line 5, in <module>
    from pepper_snp.modules.python.models.dataloader_predict import SequenceDataset
  File "/usr/local/lib/python3.6/dist-packages/pepper_snp/modules/python/models/dataloader_predict.py", line 4, in <module>
    import torchvision.transforms as transforms
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/__init__.py", line 22, in <module>
    from .kinetics import Kinetics400
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/kinetics.py", line 3, in <module>
    from .video_utils import VideoClips
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/video_utils.py", line 5, in <module>
    from torchvision.io import (
  File "/usr/local/lib/python3.6/dist-packages/torchvision/io/__init__.py", line 1, in <module>
    from .video import write_video, read_video, read_video_timestamps, _HAS_VIDEO_OPT
  File "/usr/local/lib/python3.6/dist-packages/torchvision/io/video.py", line 26, in <module>
    av.logging.set_level(av.logging.ERROR)
AttributeError: module 'av' has no attribute 'logging'
```

**Comment by kishwarshafin** [comment] 2021-03-16 00:31
@ponomarevsy 

It looks like the releases we have made do not support RHEL 7. I have tested it on Ubuntu and Debian and it works fine. It will be very difficult for us to reproduce this issue on our end, however, I will create a ticket internally to support RHEL 7 in the future.
