### ISSUE TITLE
HG002 dataset

### ISSUE THREAD

**Issue by GuillaumeHolley** [kishwarshafin/pepper#104] opened 2021-10-11 14:02 UTC
Hi,

Would it be possible to get the dataset used in [this comparison of r0.4 vs r0.5](https://twitter.com/kishwarshafin/status/1431105773589839876/photo/1)?

Thank you.

Guillaume

**Comment by kishwarshafin** [comment] 2021-10-11 15:05
@GuillaumeHolley ,

Sure, here's the dataset:
```bash
gs://pepper-deepvariant-public/quickstart_data/HG002_guppy_507_2_GRCh38_PEPPER_MARGIN.chr20.bam
gs://pepper-deepvariant-public/quickstart_data/HG002_guppy_507_2_GRCh38_PEPPER_MARGIN.chr20.bam.bai
```
Reference is GRCh38:
```bash
https://storage.googleapis.com/kishwar-helen/variant_calling_data/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
https://storage.googleapis.com/kishwar-helen/variant_calling_data/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai
```

The bams at different coverages were generated with `samtools`:
```bash
set i 30
set coverage 95
set downsample_fraction (math $i/$coverage)
samtools view -s $downsample_fraction -b -@71 HG002_guppy_507_2_GRCh38_pass.chr20.bam > HG002_guppy_507_2_GRCh38_pass.chr20.{$i}x.bam
```

**Comment by GuillaumeHolley** [comment] 2021-10-11 15:08
Thanks @kishwarshafin. I completely missed the "chr20" in the figure title... Do you have some results across all chromosomes of HG002?

**Comment by kishwarshafin** [comment] 2021-10-11 15:24
@GuillaumeHolley , 

No, because we train our model on HG002 chr1-chr19, so the results will come from the training set. Is there anything specific you are trying to do? There are newer GIAB truth set for HG005 that was unseen to the model that we can test on, but that'll take a little bit of time to align and then call.

**Comment by GuillaumeHolley** [comment] 2021-10-15 16:43
Sorry about the delay @kishwarshafin . My question here is mostly: if we run pepper on the entire HG002 dataset (all chr.), even though pepper was trained on a larger fraction of these, I am guaranteed to have at least the same results as the one reported for chr20?

**Comment by kishwarshafin** [comment] 2021-10-15 17:04
@GuillaumeHolley , yes, you should expect the whole genome numbers to be consistent with `chr20`. Are you not seeing that?

**Comment by kishwarshafin** [comment] 2021-10-25 04:26
@GuillaumeHolley , closing this issue. Please feel free to re-open if you are not seeing expected behavior.

**Closed as completed by kishwarshafin** 2021-10-25 04:26 UTC

**Comment by GuillaumeHolley** [comment] 2021-10-25 09:29
Hi @kishwarshafin,

Sorry for this, I thought I had answered this issue already. I haven't run the full dataset yet but I would have expected to see better number for chr1-19 compared to chr20 for example since the call would be made on the same data as the training set. In any case, those are just a couple thoughts I had, it is not an "issue" with PEPPER-Margin so thanks for closing this.

Guillaume

**Comment by kishwarshafin** [comment] 2021-10-25 14:40
Got it, thanks. I'll keep in mind to add whole-genome benchmarking numbers in the newer version.

**Comment by GuillaumeHolley** [comment] 2021-12-16 15:51
Hi @kishwarshafin,

So I finally ended up running r0.5 genome-wide on the HG002 150x dataset I have (Guppy 5.0.7, SUP model). I was a little bit surprised to see that the indel F1 was at around 65% whereas I would have thought it would be above 80% given the higher coverage and most calls where on the same chromosomes used for training. I also did restrict the evaluation to chr20 and I get a similar result.  Do you think the high coverage of this dataset is an issue?
